export const AUTH_LOADING = "AUTH_LOADING";
export const SONG_LOADING = "SONG_LOADING";
export const ADMIN_LOADING = "ADMIN_LOADING";
export const PAYOUT_LOADING = "PAYOUT_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGGING_IN = "LOGGING_IN";
export const AUTH_FAILED = "AUTH_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const AUTH_SUCCESS = "AUTH_SUCCESS";

export const LOAD_COUNTRIES = "LOAD_COUNTRIES";
export const COUNTRIES_LOADED = "COUNTRIES_LOADED";
export const COUNTRIES_FAILED = "COUNTRIES_FAILED";

export const SONG_REDISTRIBUTE_FAILED = "SONG_REDISTRIBUTE_FAILED";
export const SONG_REDISTRIBUTED = "SONG_REDISTRIBUTED";
export const SONG_LINK_FAILED = "SONG_LINK_FAILED";
export const SONG_LINK_LOADED = "SONG_LINK_LOADED";
export const SONG_STATUS_LOADED = "SONG_STATUS_LOADED";
export const SONG_STATUS_FAILED = "SONG_STATUS_FAILED";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTERING = "REGISTERING";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const CHANGE_USER_PASSWORD_SUCCESS = "CHANGE_USER_PASSWORD_SUCCESS";
export const CHANGE_USER_PASSWORD_FAILED = "CHANGE_USER_PASSWORD_FAILED";
export const UPDATE_PROFILE_PICTURE = "UPDATE_PROFILE_PICTURE";
export const UPDATE_PROFILE_PICTURE_FAILED = "UPDATE_PROFILE_PICTURE_FAILED";

export const DASHBOARD_LOADING = "DASHBOARD_LOADING";
export const DASHBOARD_LOADED = "DASHBOARD_LOADED";
export const DASHBOARD_FAILED = "DASHBOARD_FAILED";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_PASSWORD_FAILED = "SET_PASSWORD_FAILED";
export const SENT_EMAIL = "SENT_EMAIL";
export const SENDING_EMAIL_FAILED = "SENDING_EMAIL_FAILED";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

export const ADD_TO_PROFILE = "ADD_TO_PROFILE";
export const ADD_TO_PROFILE_FAILED = "ADD_TO_PROFILE_FAILED";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const VERIFIED = "VERIFIED";
export const VERIFY_FAILED = "VERIFY_FAILED";

export const OTP_VERIFIED = "OTP_VERIFIED";
export const OTP_VERIFY_FAILED = "OTP_VERIFY_FAILED";

export const RESEND_OTP = "RESEND_OTP";
export const RESEND_OTP_FAILED = "RESEND_OTP_FAILED";

export const UPLOADED = "UPLOADED";
export const UPLOAD_FAILED = "UPLOAD_FAILED";

export const SONG_UPLOADED = "SONG_UPLOADED";
export const SONG_UPLOAD_FAILED = "SONG_UPLOAD_FAILED";

export const SONG_LOADED = "SONG_LOADED";
export const SONG_LOAD_FAILED = "SONG_LOAD_FAILED";

export const ALBUM_LOADED = "ALBUM_LOADED";
export const ALBUM_LOAD_FAILED = "ALBUM_LOAD_FAILED";

export const SUBSCRIPTION_LOADED = "SUBSCRIPTION_LOADED";
export const SUBSCRIPTION_LOAD_FAILED = "SUBSCRIPTION_LOAD_FAILED";

export const MY_SUBSCRIPTION_LOADED = "MY_SUBSCRIPTION_LOADED";
export const MY_SUBSCRIPTION_LOAD_FAILED = "MY_SUBSCRIPTION_LOAD_FAILED";

export const SUBSCRIPTION_CREATED = "SUBSCRIPTION_CREATED";
export const SUBSCRIPTION_CREATE_FAILED = "SUBSCRIPTION_CREATE_FAILED";

export const ADD_SONG_TO_SUBSCRIPTION = "ADD_SONG_TO_SUBSCRIPTION";
export const ADD_SONG_TO_SUBSCRIPTION_FAILED =
  "ADD_SONG_TO_SUBSCRIPTION_FAILED";

export const ADDED_A_BENEFICIARY = "ADDED_A_BENEFICIARY";
export const ADDING_BENEFICIARY_FAILED = "ADDING_BENEFICIARY_FAILED";

export const ROYALTY_LINK_VERIFIED = "ROYALTY_LINK_VERIFIED";
export const ROYALTY_LINK_INVALID = "ROYALTY_LINK_INVALID";

export const ROYALTY_AUTHENTICATED = "ROYALTY_AUTHENTICATED";
export const ROYALTY_AUTHENTICATION_FAILED = "ROYALTY_AUTHENTICATION_FAILED";

export const ROYALTY_PROFILE_UPDATED = "ROYALTY_PROFILE_UPDATED";
export const ROYALTY_PROFILE_UPDATE_FAILED = "ROYALTY_PROFILE_UPDATE_FAILED";

export const ROYALTY_BANK_VERIFIED = "ROYALTY_BANK_VERIFIED";
export const ROYALTY_BANK_VERIFICATION_FAILED =
  "ROYALTY_BANK_VERIFICATION_FAILED";

export const ACCESS_LOADED = "ACCESS_LOADED";
export const ACCESS_LOADED_FAILED = "ACCESS_LOADED_FAILED";

export const GENRE_LOADED = "GENRE_LOADED";
export const GENRE_LOAD_FAILED = "GENRE_LOAD_FAILED";

export const CHARGE_LIST_LOADED = " CHARGE_LIST_LOADED";
export const CHARGE_LIST_LOAD_FAILED = "CHARGE_LIST_LOAD_FAILED";

export const CHARGE_ADDED = "CHARGE_ADDED";
export const CHARGE_ADD_FAILED = "CHARGE_ADD_FAILED";

export const CHARGE_REMOVED = "CHARGE_REMOVED";
export const CHARGE_REMOVE_FAILED = "CHARGE_REMOVE_FAILED";

export const GO_BACK_INITIATED = "GO_BACK_INITIATED";

export const PAYOUT_FOUND = "PAYOUT_FOUND";
export const PAYOUT_NOT_FOUND = "PAYOUT_NOT_FOUND";

export const TRIGGERED_SUCCESSFULLY = "TRIGGERED_SUCCESSFULLY";
export const TRIGGER_UNSUCCESSFUL = "TRIGGER_UNSUCCESSFUL";

export const CASH_OUT_INITIALIZED_SUCCESSFULLY =
  "CASH_OUT_INITIALIZED_SUCCESSFULLY";
export const CASH_OUT_INITIALIZATION_FAILED = "CASH_OUT_INITIALIZATION_FAILED";

export const GET_HISTORY_SUCCESSFULL = "GET_HISTORY_SUCCESSFULL";
export const GET_HISTORY_UNSUCCESSFUL = "GET_HISTORY_UNSUCCESSFUL";

export const GOT_FAILED_PAYOUT = "GOT_FAILED_PAYOUT";
export const FAILED_PAYOUT_FAILED = "FAILED_PAYOUT_FAILED";

export const LABEL_CREATED = "LABEL_CREATED";
export const LABEL_CREATED_FAILED = "LABEL_CREATED_FAILED";

export const LABEL_LOADED = "LABEL_LOADED";
export const LABEL_LOAD_FAILED = "LABEL_LOAD_FAILED";

export const LABEL_UPDATED = "LABEL_UPDATED";
export const LABEL_UPDATE_FAILED = "LABEL_UPDATE_FAILED";

export const LABEL_DELETED = "LABEL_DELETED";
export const LABEL_DELETE_FAILED = "LABEL_DELETE_FAILED";

export const ARTISTE_LOADED = "ARTISTE_LOADED";
export const ARTISTE_LOAD_FAIL = "ARTISTE_LOAD_FAIL";

export const ARTISTE_DELETED = "ARTISTE_DELETED";
export const ARTISTE_DELETE_FAILED = "ARTISTE_DELETE_FAILED";

export const ARTISTE_DEACTIVATED = "ARTISTE_DEACTIVATED";
export const ARTISTE_DEACTIVATE_FAILED = "ARTISTE_DEACTIVATE_FAILED";

export const SONG_DELETED = "SONG_DELETED";
export const SONG_DELETE_FAILED = "SONG_DELETE_FAILED";

export const BENEFIT_LOADED = "BENEFIT_LOADED";
export const BENEFIT_LOAD_FAILED = "BENEFIT_LOAD_FAILED";

export const BENEFICIARY_UPDATED = "BENEFICIARY_UPDATED";
export const BENEFICIARY_UPDATE_FAILED = "BENEFICIARY_UPDATE_FAILED";

export const BENEFICIARY_DELETED = "BENEFICIARY_DELETED";
export const BENEFICIARY_DELETE_FAILED = "BENEFICIARY_DELETE_FAILED";

export const CHARGE_UPDATED = "CHARGE_UPDATED";
export const CHARGE_UPDATE_FAILED = "CHARGE_UPDATE_FAILED";

export const SONG_UPDATED = "SONG_UPDATED";
export const SONG_UPDATE_FAILED = "SONG_UPDATE_FAILED";

export const CREATING_PACKAGE = "CREATING_PACKAGE";
export const PACKAGE_CREATED = "PACKAGE_CREATED";
export const PACKAGE_FAILED = "PACKAGE_FAILED";
export const PACKAGE_DELETED = "PACKAGE_DELETED";
export const PACKAGE_EDITED = "PACKAGE_EDITED";

export const ADVERT_PLAN_LOADING = "ADVERT_PLAN_LOADING";
export const CREATED_ADVERT_PLAN = "CREATED_ADVERT_PLAN";
export const ADVERT_PLAN_FAILED = "ADVERT_PLAN_FAILED";
export const ADVERT_PLAN_DELETED = "ADVERT_PLAN_DELETED";
export const ADVERT_PLAN_EDITED = "ADVERT_PLAN_EDITED";
export const ADVERT_PLAN_LOADED = "ADVERT_PLAN_LOADED";

export const ADVERT_LOADING = "ADVERT_LOADING";
export const CREATED_ADVERT = "CREATED_ADVERT";
export const ADVERT_FAILED = "ADVERT_FAILED";
export const ADVERT_DELETED = "ADVERT_DELETED";
export const ADVERT_EDITED = "ADVERT_EDITED";
export const ADVERT_LOADED = "ADVERT_LOADED";
export const ADVERT_PUBLISHED = "ADVERT_PUBLISHED";

export const SONG_SALES_SUCCESS = "SONG_SALES_SUCCESS";
export const SONG_SALES_FAILED = "SONG_SALES_FAILED";

export const MANUAL_PAYMENT_SUCCESS = "MANUAL_PAYMENT_SUCCESS";
export const MANUAL_PAYMENT_FAILED = "MANUAL_PAYMENT_FAILED";
