export default [
  {
    label: "Abia ",
    value: 1,
    locals: [
      { label: "Aba South", value: 1 },
      { label: "Arochukwu", value: 2 },
      { label: "Bende", value: 3 },
      { label: "Ikwuano", value: 4 },
      { label: "Isiala Ngwa North", value: 5 },
      { label: "Isiala Ngwa South", value: 6 },
      { label: "Isuikwuato", value: 7 },
      { label: "Obi Ngwa", value: 8 },
      { label: "Ohafia", value: 9 },
      { label: "Osisioma", value: 10 },
      { label: "Ugwunagbo", value: 11 },
      { label: "Ukwa East", value: 12 },
      { label: "Ukwa West", value: 13 },
      { label: "Umuahia North", value: 14 },
      { label: "Umuahia South", value: 15 },
      { label: "Umu Nneochi", value: 16 },
    ],
  },
  {
    label: "Adamawa ",
    value: 2,
    locals: [
      { label: "Fufure", value: 1 },
      { label: "Ganye", value: 2 },
      { label: "Gayuk", value: 3 },
      { label: "Gombi", value: 4 },
      { label: "Grie", value: 5 },
      { label: "Hong", value: 6 },
      { label: "Jada", value: 7 },
      { label: "Lamurde", value: 8 },
      { label: "Madagali", value: 9 },
      { label: "Maiha", value: 10 },
      { label: "Mayo Belwa", value: 11 },
      { label: "Michika", value: 12 },
      { label: "Mubi North", value: 13 },
      { label: "Mubi South", value: 14 },
      { label: "Numan", value: 15 },
      { label: "Shelleng", value: 16 },
      { label: "Song", value: 17 },
      { label: "Toungo", value: 18 },
      { label: "Yola North", value: 19 },
      { label: "Yola South", value: 20 },
    ],
  },
  {
    label: "Akwa Ibom ",
    value: 3,
    locals: [
      { label: "Eastern Obolo", value: 1 },
      { label: "Eket", value: 2 },
      { label: "Esit Eket", value: 3 },
      { label: "Essien Udim", value: 4 },
      { label: "Etim Ekpo", value: 5 },
      { label: "Etinan", value: 6 },
      { label: "Ibeno", value: 7 },
      { label: "Ibesikpo Asutan", value: 8 },
      { label: "Ibiono-Ibom", value: 9 },
      { label: "Ika", value: 10 },
      { label: "Ikono", value: 11 },
      { label: "Ikot Abasi", value: 12 },
      { label: "Ikot Ekpene", value: 13 },
      { label: "Ini", value: 14 },
      { label: "Itu", value: 15 },
      { label: "Mbo", value: 16 },
      { label: "Mkpat-Enin", value: 17 },
      { label: "Nsit-Atai", value: 18 },
      { label: "Nsit-Ibom", value: 19 },
      { label: "Nsit-Ubium", value: 20 },
      { label: "Obot Akara", value: 21 },
      { label: "Okobo", value: 22 },
      { label: "Onna", value: 23 },
      { label: "Oron", value: 24 },
      { label: "Oruk Anam", value: 25 },
      { label: "Udung-Uko", value: 26 },
      { label: "Ukanafun", value: 27 },
      { label: "Uruan", value: 28 },
      { label: "Urue-Offong/Oruko", value: 29 },
      { label: "Uyo", value: 30 },
    ],
  },
  {
    label: "Anambra ",
    value: 4,
    locals: [
      { label: "Anambra East", value: 1 },
      { label: "Anambra West", value: 2 },
      { label: "Anaocha", value: 3 },
      { label: "Awka North", value: 4 },
      { label: "Awka South", value: 5 },
      { label: "Ayamelum", value: 6 },
      { label: "Dunukofia", value: 7 },
      { label: "Ekwusigo", value: 8 },
      { label: "Idemili North", value: 9 },
      { label: "Idemili South", value: 10 },
      { label: "Ihiala", value: 11 },
      { label: "Njikoka", value: 12 },
      { label: "Nnewi North", value: 13 },
      { label: "Nnewi South", value: 14 },
      { label: "Ogbaru", value: 15 },
      { label: "Onitsha North", value: 16 },
      { label: "Onitsha South", value: 17 },
      { label: "Orumba North", value: 18 },
      { label: "Orumba South", value: 19 },
      { label: "Oyi", value: 20 },
    ],
  },
  {
    label: "Bauchi ",
    value: 5,
    locals: [
      { label: "Bauchi", value: 1 },
      { label: "Bogoro", value: 2 },
      { label: "Damban", value: 3 },
      { label: "Darazo", value: 4 },
      { label: "Dass", value: 5 },
      { label: "Gamawa", value: 6 },
      { label: "Ganjuwa", value: 7 },
      { label: "Giade", value: 8 },
      { label: "Itas/Gadau", value: 9 },
      { label: "Jama'are", value: 10 },
      { label: "Katagum", value: 11 },
      { label: "Kirfi", value: 12 },
      { label: "Misau", value: 13 },
      { label: "Ningi", value: 14 },
      { label: "Shira", value: 15 },
      { label: "Tafawa Balewa", value: 16 },
      { label: "Toro", value: 17 },
      { label: "Warji", value: 18 },
      { label: "Zaki", value: 19 },
    ],
  },
  {
    label: "Bayelsa ",
    value: 6,
    locals: [
      { label: "Ekeremor", value: 1 },
      { label: "Kolokuma/Opokuma", value: 2 },
      { label: "Nembe", value: 3 },
      { label: "Ogbia", value: 4 },
      { label: "Sagbama", value: 5 },
      { label: "Southern Ijaw", value: 6 },
      { label: "Yenagoa", value: 7 },
    ],
  },
  {
    label: "Benue ",
    value: 7,
    locals: [
      { label: "Apa", value: 1 },
      { label: "Ado", value: 2 },
      { label: "Buruku", value: 3 },
      { label: "Gboko", value: 4 },
      { label: "Guma", value: 5 },
      { label: "Gwer East", value: 6 },
      { label: "Gwer West", value: 7 },
      { label: "Katsina-Ala", value: 8 },
      { label: "Konshisha", value: 9 },
      { label: "Kwande", value: 10 },
      { label: "Logo", value: 11 },
      { label: "Makurdi", value: 12 },
      { label: "Obi", value: 13 },
      { label: "Ogbadibo", value: 14 },
      { label: "Ohimini", value: 15 },
      { label: "Oju", value: 16 },
      { label: "Okpokwu", value: 17 },
      { label: "Oturkpo", value: 18 },
      { label: "Tarka", value: 19 },
      { label: "Ukum", value: 20 },
      { label: "Ushongo", value: 21 },
      { label: "Vandeikya", value: 22 },
    ],
  },
  {
    label: "Borno ",
    value: 8,
    locals: [
      { label: "Askira/Uba", value: 1 },
      { label: "Bama", value: 2 },
      { label: "Bayo", value: 3 },
      { label: "Biu", value: 4 },
      { label: "Chibok", value: 5 },
      { label: "Damboa", value: 6 },
      { label: "Dikwa", value: 7 },
      { label: "Gubio", value: 8 },
      { label: "Guzamala", value: 9 },
      { label: "Gwoza", value: 10 },
      { label: "Hawul", value: 11 },
      { label: "Jere", value: 12 },
      { label: "Kaga", value: 13 },
      { label: "Kala/Balge", value: 14 },
      { label: "Konduga", value: 15 },
      { label: "Kukawa", value: 16 },
      { label: "Kwaya Kusar", value: 17 },
      { label: "Mafa", value: 18 },
      { label: "Magumeri", value: 19 },
      { label: "Maiduguri", value: 20 },
      { label: "Marte", value: 21 },
      { label: "Mobbar", value: 22 },
      { label: "Monguno", value: 23 },
      { label: "Ngala", value: 24 },
      { label: "Nganzai", value: 25 },
      { label: "Shani", value: 26 },
    ],
  },
  {
    label: "Cross River ",
    value: 9,
    locals: [
      { label: "Akamkpa", value: 1 },
      { label: "Akpabuyo", value: 2 },
      { label: "Bakassi", value: 3 },
      { label: "Bekwarra", value: 4 },
      { label: "Biase", value: 5 },
      { label: "Boki", value: 6 },
      { label: "Calabar Municipal", value: 7 },
      { label: "Calabar South", value: 8 },
      { label: "Etung", value: 9 },
      { label: "Ikom", value: 10 },
      { label: "Obanliku", value: 11 },
      { label: "Obubra", value: 12 },
      { label: "Obudu", value: 13 },
      { label: "Odukpani", value: 14 },
      { label: "Ogoja", value: 15 },
      { label: "Yakuur", value: 16 },
      { label: "Yala", value: 17 },
    ],
  },
  {
    label: "Delta ",
    value: 10,
    locals: [
      { label: "Aniocha South", value: 1 },
      { label: "Bomadi", value: 2 },
      { label: "Burutu", value: 3 },
      { label: "Ethiope East", value: 4 },
      { label: "Ethiope West", value: 5 },
      { label: "Ika North East", value: 6 },
      { label: "Ika South", value: 7 },
      { label: "Isoko North", value: 8 },
      { label: "Isoko South", value: 9 },
      { label: "Ndokwa East", value: 10 },
      { label: "Ndokwa West", value: 11 },
      { label: "Okpe", value: 12 },
      { label: "Oshimili North", value: 13 },
      { label: "Oshimili South", value: 14 },
      { label: "Patani", value: 15 },
      { label: "Sapele", value: 16 },
      { label: "Udu", value: 17 },
      { label: "Ughelli North", value: 18 },
      { label: "Ughelli South", value: 19 },
      { label: "Ukwuani", value: 20 },
      { label: "Uvwie", value: 21 },
      { label: "Warri North", value: 22 },
      { label: "Warri South", value: 23 },
      { label: "Warri South West", value: 24 },
    ],
  },
  {
    label: "Ebonyi ",
    value: 11,
    locals: [
      { label: "Afikpo North", value: 1 },
      { label: "Afikpo South", value: 2 },
      { label: "Ebonyi", value: 3 },
      { label: "Ezza North", value: 4 },
      { label: "Ezza South", value: 5 },
      { label: "Ikwo", value: 6 },
      { label: "Ishielu", value: 7 },
      { label: "Ivo", value: 8 },
      { label: "Izzi", value: 9 },
      { label: "Ohaozara", value: 10 },
      { label: "Ohaukwu", value: 11 },
      { label: "Onicha", value: 12 },
    ],
  },
  {
    label: "Edo ",
    value: 12,
    locals: [
      { label: "Egor", value: 1 },
      { label: "Esan Central", value: 2 },
      { label: "Esan North-East", value: 3 },
      { label: "Esan South-East", value: 4 },
      { label: "Esan West", value: 5 },
      { label: "Etsako Central", value: 6 },
      { label: "Etsako East", value: 7 },
      { label: "Etsako West", value: 8 },
      { label: "Igueben", value: 9 },
      { label: "Ikpoba Okha", value: 10 },
      { label: "Orhionmwon", value: 11 },
      { label: "Oredo", value: 12 },
      { label: "Ovia North-East", value: 13 },
      { label: "Ovia South-West", value: 14 },
      { label: "Owan East", value: 15 },
      { label: "Owan West", value: 16 },
      { label: "Uhunmwonde", value: 17 },
    ],
  },
  {
    label: "Ekiti ",
    value: 13,
    locals: [
      { label: "Efon", value: 1 },
      { label: "Ekiti East", value: 2 },
      { label: "Ekiti South-West", value: 3 },
      { label: "Ekiti West", value: 4 },
      { label: "Emure", value: 5 },
      { label: "Gbonyin", value: 6 },
      { label: "Ido Osi", value: 7 },
      { label: "Ijero", value: 8 },
      { label: "Ikere", value: 9 },
      { label: "Ikole", value: 10 },
      { label: "Ilejemeje", value: 11 },
      { label: "Irepodun/Ifelodun", value: 12 },
      { label: "Ise/Orun", value: 13 },
      { label: "Moba", value: 14 },
      { label: "Oye", value: 15 },
    ],
  },
  {
    label: "Enugu ",
    value: 14,
    locals: [
      { label: "Awgu", value: 1 },
      { label: "Enugu East", value: 2 },
      { label: "Enugu North", value: 3 },
      { label: "Enugu South", value: 4 },
      { label: "Ezeagu", value: 5 },
      { label: "Igbo Etiti", value: 6 },
      { label: "Igbo Eze North", value: 7 },
      { label: "Igbo Eze South", value: 8 },
      { label: "Isi Uzo", value: 9 },
      { label: "Nkanu East", value: 10 },
      { label: "Nkanu West", value: 11 },
      { label: "Nsukka", value: 12 },
      { label: "Oji River", value: 13 },
      { label: "Udenu", value: 14 },
      { label: "Udi", value: 15 },
      { label: "Uzo Uwani", value: 16 },
    ],
  },
  {
    label: "FCT",
    value: 15,
    locals: [
      { label: "Bwari", value: 1 },
      { label: "Gwagwalada", value: 2 },
      { label: "Kuje", value: 3 },
      { label: "Kwali", value: 4 },
      { label: "Municipal Area Council", value: 5 },
    ],
  },
  {
    label: "Gombe ",
    value: 16,
    locals: [
      { label: "Balanga", value: 1 },
      { label: "Billiri", value: 2 },
      { label: "Dukku", value: 3 },
      { label: "Funakaye", value: 4 },
      { label: "Gombe", value: 5 },
      { label: "Kaltungo", value: 6 },
      { label: "Kwami", value: 7 },
      { label: "Nafada", value: 8 },
      { label: "Shongom", value: 9 },
      { label: "Yamaltu/Deba", value: 10 },
    ],
  },
  {
    label: "Imo ",
    value: 17,
    locals: [
      { label: "Ahiazu Mbaise", value: 1 },
      { label: "Ehime Mbano", value: 2 },
      { label: "Ezinihitte", value: 3 },
      { label: "Ideato North", value: 4 },
      { label: "Ideato South", value: 5 },
      { label: "Ihitte/Uboma", value: 6 },
      { label: "Ikeduru", value: 7 },
      { label: "Isiala Mbano", value: 8 },
      { label: "Isu", value: 9 },
      { label: "Mbaitoli", value: 10 },
      { label: "Ngor Okpala", value: 11 },
      { label: "Njaba", value: 12 },
      { label: "Nkwerre", value: 13 },
      { label: "Nwangele", value: 14 },
      { label: "Obowo", value: 15 },
      { label: "Oguta", value: 16 },
      { label: "Ohaji/Egbema", value: 17 },
      { label: "Okigwe", value: 18 },
      { label: "Orlu", value: 19 },
      { label: "Orsu", value: 20 },
      { label: "Oru East", value: 21 },
      { label: "Oru West", value: 22 },
      { label: "Owerri Municipal", value: 23 },
      { label: "Owerri North", value: 24 },
      { label: "Owerri West", value: 25 },
      { label: "Unuimo", value: 26 },
    ],
  },
  {
    label: "Jigawa ",
    value: 18,
    locals: [
      { label: "Babura", value: 1 },
      { label: "Biriniwa", value: 2 },
      { label: "Birnin Kudu", value: 3 },
      { label: "Buji", value: 4 },
      { label: "Dutse", value: 5 },
      { label: "Gagarawa", value: 6 },
      { label: "Garki", value: 7 },
      { label: "Gumel", value: 8 },
      { label: "Guri", value: 9 },
      { label: "Gwaram", value: 10 },
      { label: "Gwiwa", value: 11 },
      { label: "Hadejia", value: 12 },
      { label: "Jahun", value: 13 },
      { label: "Kafin Hausa", value: 14 },
      { label: "Kazaure", value: 15 },
      { label: "Kiri Kasama", value: 16 },
      { label: "Kiyawa", value: 17 },
      { label: "Kaugama", value: 18 },
      { label: "Maigatari", value: 19 },
      { label: "Malam Madori", value: 20 },
      { label: "Miga", value: 21 },
      { label: "Ringim", value: 22 },
      { label: "Roni", value: 23 },
      { label: "Sule Tankarkar", value: 24 },
      { label: "Taura", value: 25 },
      { label: "Yankwashi", value: 26 },
    ],
  },
  {
    label: "Kaduna ",
    value: 19,
    locals: [
      { label: "Chikun", value: 1 },
      { label: "Giwa", value: 2 },
      { label: "Igabi", value: 3 },
      { label: "Ikara", value: 4 },
      { label: "Jaba", value: 5 },
      { label: "Jema'a", value: 6 },
      { label: "Kachia", value: 7 },
      { label: "Kaduna North", value: 8 },
      { label: "Kaduna South", value: 9 },
      { label: "Kagarko", value: 10 },
      { label: "Kajuru", value: 11 },
      { label: "Kaura", value: 12 },
      { label: "Kauru", value: 13 },
      { label: "Kubau", value: 14 },
      { label: "Kudan", value: 15 },
      { label: "Lere", value: 16 },
      { label: "Makarfi", value: 17 },
      { label: "Sabon Gari", value: 18 },
      { label: "Sanga", value: 19 },
      { label: "Soba", value: 20 },
      { label: "Zangon Kataf", value: 21 },
      { label: "Zaria", value: 22 },
    ],
  },
  {
    label: "Kano ",
    value: 20,
    locals: [
      { label: "Albasu", value: 1 },
      { label: "Bagwai", value: 2 },
      { label: "Bebeji", value: 3 },
      { label: "Bichi", value: 4 },
      { label: "Bunkure", value: 5 },
      { label: "Dala", value: 6 },
      { label: "Dambatta", value: 7 },
      { label: "Dawakin Kudu", value: 8 },
      { label: "Dawakin Tofa", value: 9 },
      { label: "Doguwa", value: 10 },
      { label: "Fagge", value: 11 },
      { label: "Gabasawa", value: 12 },
      { label: "Garko", value: 13 },
      { label: "Garun Mallam", value: 14 },
      { label: "Gaya", value: 15 },
      { label: "Gezawa", value: 16 },
      { label: "Gwale", value: 17 },
      { label: "Gwarzo", value: 18 },
      { label: "Kabo", value: 19 },
      { label: "Kano Municipal", value: 20 },
      { label: "Karaye", value: 21 },
      { label: "Kibiya", value: 22 },
      { label: "Kiru", value: 23 },
      { label: "Kumbotso", value: 24 },
      { label: "Kunchi", value: 25 },
      { label: "Kura", value: 26 },
      { label: "Madobi", value: 27 },
      { label: "Makoda", value: 28 },
      { label: "Minjibir", value: 29 },
      { label: "Nasarawa", value: 30 },
      { label: "Rano", value: 31 },
      { label: "Rimin Gado", value: 32 },
      { label: "Rogo", value: 33 },
      { label: "Shanono", value: 34 },
      { label: "Sumaila", value: 35 },
      { label: "Takai", value: 36 },
      { label: "Tarauni", value: 37 },
      { label: "Tofa", value: 38 },
      { label: "Tsanyawa", value: 39 },
      { label: "Tudun Wada", value: 40 },
      { label: "Ungogo", value: 41 },
      { label: "Warawa", value: 42 },
      { label: "Wudil", value: 43 },
    ],
  },
  {
    label: "Katsina ",
    value: 21,
    locals: [
      { label: "Batagarawa", value: 1 },
      { label: "Batsari", value: 2 },
      { label: "Baure", value: 3 },
      { label: "Bindawa", value: 4 },
      { label: "Charanchi", value: 5 },
      { label: "Dandume", value: 6 },
      { label: "Danja", value: 7 },
      { label: "Dan Musa", value: 8 },
      { label: "Daura", value: 9 },
      { label: "Dutsi", value: 10 },
      { label: "Dutsin Ma", value: 11 },
      { label: "Faskari", value: 12 },
      { label: "Funtua", value: 13 },
      { label: "Ingawa", value: 14 },
      { label: "Jibia", value: 15 },
      { label: "Kafur", value: 16 },
      { label: "Kaita", value: 17 },
      { label: "Kankara", value: 18 },
      { label: "Kankia", value: 19 },
      { label: "Katsina", value: 20 },
      { label: "Kurfi", value: 21 },
      { label: "Kusada", value: 22 },
      { label: "Mai'Adua", value: 23 },
      { label: "Malumfashi", value: 24 },
      { label: "Mani", value: 25 },
      { label: "Mashi", value: 26 },
      { label: "Matazu", value: 27 },
      { label: "Musawa", value: 28 },
      { label: "Rimi", value: 29 },
      { label: "Sabuwa", value: 30 },
      { label: "Safana", value: 31 },
      { label: "Sandamu", value: 32 },
      { label: "Zango", value: 33 },
    ],
  },
  {
    label: "Kebbi ",
    value: 22,
    locals: [
      { label: "Arewa Dandi", value: 1 },
      { label: "Argungu", value: 2 },
      { label: "Augie", value: 3 },
      { label: "Bagudo", value: 4 },
      { label: "Birnin Kebbi", value: 5 },
      { label: "Bunza", value: 6 },
      { label: "Dandi", value: 7 },
      { label: "Fakai", value: 8 },
      { label: "Gwandu", value: 9 },
      { label: "Jega", value: 10 },
      { label: "Kalgo", value: 11 },
      { label: "Koko/Besse", value: 12 },
      { label: "Maiyama", value: 13 },
      { label: "Ngaski", value: 14 },
      { label: "Sakaba", value: 15 },
      { label: "Shanga", value: 16 },
      { label: "Suru", value: 17 },
      { label: "Wasagu/Danko", value: 18 },
      { label: "Yauri", value: 19 },
      { label: "Zuru", value: 20 },
    ],
  },
  {
    label: "Kogi ",
    value: 23,
    locals: [
      { label: "Ajaokuta", value: 1 },
      { label: "Ankpa", value: 2 },
      { label: "Bassa", value: 3 },
      { label: "Dekina", value: 4 },
      { label: "Ibaji", value: 5 },
      { label: "Idah", value: 6 },
      { label: "Igalamela Odolu", value: 7 },
      { label: "Ijumu", value: 8 },
      { label: "Kabba/Bunu", value: 9 },
      { label: "Kogi", value: 10 },
      { label: "Lokoja", value: 11 },
      { label: "Mopa Muro", value: 12 },
      { label: "Ofu", value: 13 },
      { label: "Ogori/Magongo", value: 14 },
      { label: "Okehi", value: 15 },
      { label: "Okene", value: 16 },
      { label: "Olamaboro", value: 17 },
      { label: "Omala", value: 18 },
      { label: "Yagba East", value: 19 },
      { label: "Yagba West", value: 20 },
    ],
  },
  {
    label: "Kwara ",
    value: 24,
    locals: [
      { label: "Baruten", value: 1 },
      { label: "Edu", value: 2 },
      { label: "Ekiti", value: 3 },
      { label: "Ifelodun", value: 4 },
      { label: "Ilorin East", value: 5 },
      { label: "Ilorin South", value: 6 },
      { label: "Ilorin West", value: 7 },
      { label: "Irepodun", value: 8 },
      { label: "Isin", value: 9 },
      { label: "Kaiama", value: 10 },
      { label: "Moro", value: 11 },
      { label: "Offa", value: 12 },
      { label: "Oke Ero", value: 13 },
      { label: "Oyun", value: 14 },
      { label: "Pategi", value: 15 },
    ],
  },
  {
    label: "Lagos ",
    value: 25,
    locals: [
      { label: "Ajeromi-Ifelodun", value: 1 },
      { label: "Alimosho", value: 2 },
      { label: "Amuwo-Odofin", value: 3 },
      { label: "Apapa", value: 4 },
      { label: "Badagry", value: 5 },
      { label: "Epe", value: 6 },
      { label: "Eti Osa", value: 7 },
      { label: "Ibeju-Lekki", value: 8 },
      { label: "Ifako-Ijaiye", value: 9 },
      { label: "Ikeja", value: 10 },
      { label: "Ikorodu", value: 11 },
      { label: "Kosofe", value: 12 },
      { label: "Lagos Island", value: 13 },
      { label: "Lagos Mainland", value: 14 },
      { label: "Mushin", value: 15 },
      { label: "Ojo", value: 16 },
      { label: "Oshodi-Isolo", value: 17 },
      { label: "Shomolu", value: 18 },
      { label: "Surulere", value: 19 },
    ],
  },
  {
    label: "Nasarawa ",
    value: 26,
    locals: [
      { label: "Awe", value: 1 },
      { label: "Doma", value: 2 },
      { label: "Karu", value: 3 },
      { label: "Keana", value: 4 },
      { label: "Keffi", value: 5 },
      { label: "Kokona", value: 6 },
      { label: "Lafia", value: 7 },
      { label: "Nasarawa", value: 8 },
      { label: "Nasarawa Egon", value: 9 },
      { label: "Obi", value: 10 },
      { label: "Toto", value: 11 },
      { label: "Wamba", value: 12 },
    ],
  },
  {
    label: "Niger ",
    value: 27,
    locals: [
      { label: "Agwara", value: 1 },
      { label: "Bida", value: 2 },
      { label: "Borgu", value: 3 },
      { label: "Bosso", value: 4 },
      { label: "Chanchaga", value: 5 },
      { label: "Edati", value: 6 },
      { label: "Gbako", value: 7 },
      { label: "Gurara", value: 8 },
      { label: "Katcha", value: 9 },
      { label: "Kontagora", value: 10 },
      { label: "Lapai", value: 11 },
      { label: "Lavun", value: 12 },
      { label: "Magama", value: 13 },
      { label: "Mariga", value: 14 },
      { label: "Mashegu", value: 15 },
      { label: "Mokwa", value: 16 },
      { label: "Moya", value: 17 },
      { label: "Paikoro", value: 18 },
      { label: "Rafi", value: 19 },
      { label: "Rijau", value: 20 },
      { label: "Shiroro", value: 21 },
      { label: "Suleja", value: 22 },
      { label: "Tafa", value: 23 },
      { label: "Wushishi", value: 24 },
    ],
  },
  {
    label: "Ogun ",
    value: 28,
    locals: [
      { label: "Abeokuta South", value: 1 },
      { label: "Ado-Odo/Ota", value: 2 },
      { label: "Egbado North", value: 3 },
      { label: "Egbado South", value: 4 },
      { label: "Ewekoro", value: 5 },
      { label: "Ifo", value: 6 },
      { label: "Ijebu East", value: 7 },
      { label: "Ijebu North", value: 8 },
      { label: "Ijebu North East", value: 9 },
      { label: "Ijebu Ode", value: 10 },
      { label: "Ikenne", value: 11 },
      { label: "Imeko Afon", value: 12 },
      { label: "Ipokia", value: 13 },
      { label: "Obafemi Owode", value: 14 },
      { label: "Odeda", value: 15 },
      { label: "Odogbolu", value: 16 },
      { label: "Ogun Waterside", value: 17 },
      { label: "Remo North", value: 18 },
      { label: "Shagamu", value: 19 },
    ],
  },
  {
    label: "Ondo ",
    value: 29,
    locals: [
      { label: "Akoko North-West", value: 1 },
      { label: "Akoko South-West", value: 2 },
      { label: "Akoko South-East", value: 3 },
      { label: "Akure North", value: 4 },
      { label: "Akure South", value: 5 },
      { label: "Ese Odo", value: 6 },
      { label: "Idanre", value: 7 },
      { label: "Ifedore", value: 8 },
      { label: "Ilaje", value: 9 },
      { label: "Ile Oluji/Okeigbo", value: 10 },
      { label: "Irele", value: 11 },
      { label: "Odigbo", value: 12 },
      { label: "Okitipupa", value: 13 },
      { label: "Ondo East", value: 14 },
      { label: "Ondo West", value: 15 },
      { label: "Ose", value: 16 },
      { label: "Owo", value: 17 },
    ],
  },
  {
    label: "Osun ",
    value: 30,
    locals: [
      { label: "Atakunmosa West", value: 1 },
      { label: "Aiyedaade", value: 2 },
      { label: "Aiyedire", value: 3 },
      { label: "Boluwaduro", value: 4 },
      { label: "Boripe", value: 5 },
      { label: "Ede North", value: 6 },
      { label: "Ede South", value: 7 },
      { label: "Ife Central", value: 8 },
      { label: "Ife East", value: 9 },
      { label: "Ife North", value: 10 },
      { label: "Ife South", value: 11 },
      { label: "Egbedore", value: 12 },
      { label: "Ejigbo", value: 13 },
      { label: "Ifedayo", value: 14 },
      { label: "Ifelodun", value: 15 },
      { label: "Ila", value: 16 },
      { label: "Ilesa East", value: 17 },
      { label: "Ilesa West", value: 18 },
      { label: "Irepodun", value: 19 },
      { label: "Irewole", value: 20 },
      { label: "Isokan", value: 21 },
      { label: "Iwo", value: 22 },
      { label: "Obokun", value: 23 },
      { label: "Odo Otin", value: 24 },
      { label: "Ola Oluwa", value: 25 },
      { label: "Olorunda", value: 26 },
      { label: "Oriade", value: 27 },
      { label: "Orolu", value: 28 },
      { label: "Osogbo", value: 29 },
    ],
  },
  {
    label: "Oyo ",
    value: 31,
    locals: [
      { label: "Akinyele", value: 1 },
      { label: "Atiba", value: 2 },
      { label: "Atisbo", value: 3 },
      { label: "Egbeda", value: 4 },
      { label: "Ibadan North", value: 5 },
      { label: "Ibadan North-East", value: 6 },
      { label: "Ibadan North-West", value: 7 },
      { label: "Ibadan South-East", value: 8 },
      { label: "Ibadan South-West", value: 9 },
      { label: "Ibarapa Central", value: 10 },
      { label: "Ibarapa East", value: 11 },
      { label: "Ibarapa North", value: 12 },
      { label: "Ido", value: 13 },
      { label: "Irepo", value: 14 },
      { label: "Iseyin", value: 15 },
      { label: "Itesiwaju", value: 16 },
      { label: "Iwajowa", value: 17 },
      { label: "Kajola", value: 18 },
      { label: "Lagelu", value: 19 },
      { label: "Ogbomosho North", value: 20 },
      { label: "Ogbomosho South", value: 21 },
      { label: "Ogo Oluwa", value: 22 },
      { label: "Olorunsogo", value: 23 },
      { label: "Oluyole", value: 24 },
      { label: "Ona Ara", value: 25 },
      { label: "Orelope", value: 26 },
      { label: "Ori Ire", value: 27 },
      { label: "Oyo", value: 28 },
      { label: "Oyo East", value: 29 },
      { label: "Saki East", value: 30 },
      { label: "Saki West", value: 31 },
      { label: "Surulere", value: 32 },
    ],
  },
  {
    label: "Plateau ",
    value: 32,
    locals: [
      { label: "Barkin Ladi", value: 1 },
      { label: "Bassa", value: 2 },
      { label: "Jos East", value: 3 },
      { label: "Jos North", value: 4 },
      { label: "Jos South", value: 5 },
      { label: "Kanam", value: 6 },
      { label: "Kanke", value: 7 },
      { label: "Langtang South", value: 8 },
      { label: "Langtang North", value: 9 },
      { label: "Mangu", value: 10 },
      { label: "Mikang", value: 11 },
      { label: "Pankshin", value: 12 },
      { label: "Qua'an Pan", value: 13 },
      { label: "Riyom", value: 14 },
      { label: "Shendam", value: 15 },
      { label: "Wase", value: 16 },
    ],
  },
  {
    label: "Rivers ",
    value: 33,
    locals: [
      { label: "Ahoada East", value: 1 },
      { label: "Ahoada West", value: 2 },
      { label: "Akuku-Toru", value: 3 },
      { label: "Andoni", value: 4 },
      { label: "Asari-Toru", value: 5 },
      { label: "Bonny", value: 6 },
      { label: "Degema", value: 7 },
      { label: "Eleme", value: 8 },
      { label: "Emuoha", value: 9 },
      { label: "Etche", value: 10 },
      { label: "Gokana", value: 11 },
      { label: "Ikwerre", value: 12 },
      { label: "Khana", value: 13 },
      { label: "Obio/Akpor", value: 14 },
      { label: "Ogba/Egbema/Ndoni", value: 15 },
      { label: "Ogu/Bolo", value: 16 },
      { label: "Okrika", value: 17 },
      { label: "Omuma", value: 18 },
      { label: "Opobo/Nkoro", value: 19 },
      { label: "Oyigbo", value: 20 },
      { label: "Port Harcourt", value: 21 },
      { label: "Tai", value: 22 },
    ],
  },
  {
    label: "Sokoto ",
    value: 34,
    locals: [
      { label: "Bodinga", value: 1 },
      { label: "Dange Shuni", value: 2 },
      { label: "Gada", value: 3 },
      { label: "Goronyo", value: 4 },
      { label: "Gudu", value: 5 },
      { label: "Gwadabawa", value: 6 },
      { label: "Illela", value: 7 },
      { label: "Isa", value: 8 },
      { label: "Kebbe", value: 9 },
      { label: "Kware", value: 10 },
      { label: "Rabah", value: 11 },
      { label: "Sabon Birni", value: 12 },
      { label: "Shagari", value: 13 },
      { label: "Silame", value: 14 },
      { label: "Sokoto North", value: 15 },
      { label: "Sokoto South", value: 16 },
      { label: "Tambuwal", value: 17 },
      { label: "Tangaza", value: 18 },
      { label: "Tureta", value: 19 },
      { label: "Wamako", value: 20 },
      { label: "Wurno", value: 21 },
      { label: "Yabo", value: 22 },
    ],
  },
  {
    label: "Taraba ",
    value: 35,
    locals: [
      { label: "Bali", value: 1 },
      { label: "Donga", value: 2 },
      { label: "Gashaka", value: 3 },
      { label: "Gassol", value: 4 },
      { label: "Ibi", value: 5 },
      { label: "Jalingo", value: 6 },
      { label: "Karim Lamido", value: 7 },
      { label: "Kumi", value: 8 },
      { label: "Lau", value: 9 },
      { label: "Sardauna", value: 10 },
      { label: "Takum", value: 11 },
      { label: "Ussa", value: 12 },
      { label: "Wukari", value: 13 },
      { label: "Yorro", value: 14 },
      { label: "Zing", value: 15 },
    ],
  },
  {
    label: "Yobe ",
    value: 36,
    locals: [
      { label: "Bursari", value: 1 },
      { label: "Damaturu", value: 2 },
      { label: "Fika", value: 3 },
      { label: "Fune", value: 4 },
      { label: "Geidam", value: 5 },
      { label: "Gujba", value: 6 },
      { label: "Gulani", value: 7 },
      { label: "Jakusko", value: 8 },
      { label: "Karasuwa", value: 9 },
      { label: "Machina", value: 10 },
      { label: "Nangere", value: 11 },
      { label: "Nguru", value: 12 },
      { label: "Potiskum", value: 13 },
      { label: "Tarmuwa", value: 14 },
      { label: "Yunusari", value: 15 },
      { label: "Yusufari", value: 16 },
    ],
  },
  {
    label: "Zamfara ",
    value: 37,
    locals: [
      { label: "Bakura", value: 1 },
      { label: "Birnin Magaji/Kiyaw", value: 2 },
      { label: "Bukkuyum", value: 3 },
      { label: "Bungudu", value: 4 },
      { label: "Gummi", value: 5 },
      { label: "Gusau", value: 6 },
      { label: "Kaura Namoda", value: 7 },
      { label: "Maradun", value: 8 },
      { label: "Maru", value: 9 },
      { label: "Shinkafi", value: 10 },
      { label: "Talata Mafara", value: 11 },
      { label: "Chafe", value: 12 },
      { label: "Zurmi", value: 13 },
    ],
  },
];
